# This is a basic workflow to help you get started with Actions

name: concurrency-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Sleep 60s
        run: sleep 60s
        shell: bash
